In [3]:
#Q1.
import numpy as np
lst = np.array([2, 3, 2, 2, 2, 1,0])
arr = np.zeros((lst.size, lst.max()+1))
arr[np.arange(lst.size),lst] = 1
print(arr)

[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [6]:
#Q2.
import numpy as np
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
print("Original array:")
print(arr)
print("After Removing All Empty Elements of the  array")
st = ((arr[~np.isnan(arr)]))
values = ','.join([str(i) for i in st])
print(st)

Original array:
[ 1.  2.  3. nan  5.  6.  7. nan]
After Removing All Empty Elements of the  array
[1. 2. 3. 5. 6. 7.]


In [ ]:
#Q3.
import numpy as np
from scipy.signal import argrelextrema
data = np.array([1, 3, 7, 1, 2, 6, 0, 1])
maximums = signal.argrelextrema(data, np.greater)
print(maximums)

In [13]:
#Q4.
def gen_strides(a, strides=5, w=5):
    n_strides = ((a.size-w)//strides) + 1
    return np.array([a[s:(s+w)] for s in np.arange(0, n_strides*strides, strides)])
arr = (gen_strides(np.arange(15), strides=2, w=4))
print(arr)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
