## This file is created to understand the Numpy Module 
(c) Dr. Naveen Aggarwal

#### NumPy is the fundamental package for scientific computing with Python. It contains among other things:
##### a powerful N-dimensional array object
##### sophisticated (broadcasting) functions
##### tools for integrating C/C++ and Fortran code
##### useful linear algebra, Fourier transform, and random number capabilities

In [1]:
import numpy as np

In [2]:
a=np.array([1,3,5,7,9])
b=np.array([3,5,6,7,9])
c=a+b
print(c)
d=a+2
print(d)

[ 4  8 11 14 18]
[ 3  5  7  9 11]


### Now check the type of the c

In [3]:
type(c)

numpy.ndarray

### Now check the shape of c


In [4]:
c.shape

(5,)

### There are two ways of creating matrices.
#### First is to create list and then convert into numpy array

In [7]:
# create a list 
l = [[1, 2, 3], [3, 6, 9], [2, 4, 6]]  
# convert a list to an array
a = np.array(l)   
print(a)
# Shape and Data Type
print(a.shape)
print(a.dtype)

[[1 2 3]
 [3 6 9]
 [2 4 6]]
(3, 3)
int32


#### Second way is to create direct array simple or complex

In [8]:
a = np.array([[1, 2], [3, 4]])
print(a)
# Shape and Data Type
print(a.shape)
print(a.dtype)

[[1 2]
 [3 4]]
(2, 2)
int32


#### Creating complex array

In [9]:
a = np.array([[1, 2], [3, 4]], dtype=complex)
print(a)
# Shape and Data Type
print(a.shape)
print(a.dtype)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
(2, 2)
complex128


### Accesing the Array elements

In [10]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# This is just like a list of lists 
print(a[2])  

[7 8 9]


In [10]:
# arrays can be given comma separated indices
print(a[1, 2])

6


In [11]:
# and slices
print(a[1, 1:3])

[5 6]


In [12]:
print(a[:,1])

[2 5 8]


In [13]:
#changing the values in array
a[1, 2] = 7 
print(a) 

[[1 2 3]
 [4 5 7]
 [7 8 9]]


In [14]:
a[:, 0] = [0, 9, 8] 
print(a) 

[[0 2 3]
 [9 5 7]
 [8 8 9]]


### Examples of Array Generating Functions

In [15]:
x = np.arange(0, 10, 2) # arguments: start, stop, step
print(x)
y=np.linspace(0, 10, 100, dtype=np.int) #
print(y)
z=np.logspace(0, 10, 10, base=10)
print(z)

[0 2 4 6 8]
[ 0  0  0  0  0  0  0  0  0  0  1  1  1  1  1  1  1  1  1  1  2  2  2  2
  2  2  2  2  2  2  3  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4
  4  4  5  5  5  5  5  5  5  5  5  5  6  6  6  6  6  6  6  6  6  6  7  7
  7  7  7  7  7  7  7  7  8  8  8  8  8  8  8  8  8  8  9  9  9  9  9  9
  9  9  9 10]
[1.00000000e+00 1.29154967e+01 1.66810054e+02 2.15443469e+03
 2.78255940e+04 3.59381366e+05 4.64158883e+06 5.99484250e+07
 7.74263683e+08 1.00000000e+10]


In [16]:
# a diagonal matrix
z=np.diag([1,2,3])
print(z)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [17]:
#By Default it creates floating array
b = np.zeros(5)
c=np.ones(5)
print(b,c) 
print(b.dtype)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.]
float64


In [18]:
#Tocreate integer array
my_int_array = np.zeros(10, dtype=np.int) 
print(my_int_array)
print(my_int_array.dtype)

[0 0 0 0 0 0 0 0 0 0]
int32


In [11]:
#Working with arange
d=np.arange(5)  #just like range(), It generates int array 
print(d) 

# arrays keep their type even if elements changed 
d[1] = 9.7 
print(d)  

# operations create a new array, with new type 

print(d*0.4)  
print(d.dtype)

#creating float array
d = np.arange(5, dtype=np.float)  
print(d, d.dtype) 

# arbitrary start, stop and step
d=np.arange(3, 7, 0.5) 
print(d)


[0 1 2 3 4]
[0 9 2 3 4]
[0.  3.6 0.8 1.2 1.6]
int32
[0. 1. 2. 3. 4.] float64
[3.  3.5 4.  4.5 5.  5.5 6.  6.5]


### Other ways to create Arrays

In [12]:

x, y = np.mgrid[0:5, 0:5] # similar to meshgrid in MATLAB
print(x)
print(y)



[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### Creating random array

In [13]:

z=np.random.rand(5,5)
print(z)

[[0.8469944  0.39415217 0.18230933 0.51349582 0.36822051]
 [0.17732524 0.56808604 0.1110386  0.90869618 0.89515035]
 [0.75686123 0.14163566 0.90866459 0.573432   0.95293154]
 [0.68136942 0.7060054  0.21368383 0.34400836 0.81300251]
 [0.98795976 0.88781194 0.80809281 0.85750473 0.88636779]]


### Mutable Arrays
There are three cases to be discussed for copying an array

In [14]:
# Case 1
x = np.array([1,2,3,4])
#First way to Copy
x1 = x
print(x1)
#Second way to Copy
x2=x[:]
print(x2)
#Third way to copy
x3=x.copy()
print(x3)


[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [15]:
#checking Equivalence
print(x is x1)
print (x is x2)
print(x is x3)


True
False
False


In [16]:
#Checking their ids
print(id(x), id(x1), id(x2), id(x3))

1705302127040 1705302127040 1705302129040 1705302127200


In [17]:
#Changing X affects Y

x[0] = 4
print(x1)
print(x2)
print(x3)

[4 2 3 4]
[4 2 3 4]
[1 2 3 4]


### Array Functions

In [18]:
a=np.arange(1,10,1)
print(a)
# Taking sum of all elements
print("Sum of all elements is",a.sum())
#Taking mean
print("Mean of Array is ", a.mean())
#Std Dev 
print('Std Dev of array is ', a.std())

#Smallest and largest element
print("Smallest element is", a.min(),"and Largest is ", a.max())

[1 2 3 4 5 6 7 8 9]
Sum of all elements is 45
Mean of Array is  5.0
Std Dev of array is  2.581988897471611
Smallest element is 1 and Largest is  9


### Sorting An Array

In [19]:
#First way
a=np.array([2,4,3,9,6,5,1])

a.sort()
print(a)
print(np.sort(a)[::-1])


[1 2 3 4 5 6 9]
[9 6 5 4 3 2 1]


In [20]:
#Second way by storing the arguments of sorted array
#Ascending
b=np.argsort(a)
#Descending
c=np.argsort(-a)

print(a[b])
print(a[c])

[1 2 3 4 5 6 9]
[9 6 5 4 3 2 1]


### Matrix Operations on Arrays

In [29]:
a=np.array([[2,3],[7,8]])
print(a)
b=np.eye(2)
print(b)

[[2 3]
 [7 8]]
[[1. 0.]
 [0. 1.]]


In [30]:
# transpose of matrix
print(a.transpose())

[[2 7]
 [3 8]]


In [31]:
# Inverse of matrix
from numpy.linalg import inv
print(inv(a))

[[-1.6  0.6]
 [ 1.4 -0.4]]


In [32]:
#product of two matrices
c=np.dot(a,b)
print(c)

[[2. 3.]
 [7. 8.]]


### Converting Array into matrices

In [33]:
a = np.array([[1,2],[3,4]]) 
m1 = np.mat(a) # convert 2-d array to matrix 
m = np.matrix([[1, 2], [3, 4]]) 
print(a)
print(m1)
print(m)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


### Difference between Operatons on Array and Matrices

In [34]:
# Normal Array result is 1-dimensional 
print(a[0])

[1 2]


In [35]:
# On Matrix, result is 2-dimensional 
print(m[0]) 

[[1 2]]


In [36]:
# element-by-element multiplication on Normal Array
print(a*a) 
# (algebraic) matrix multiplication on Matrix
print(m*m)

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [37]:
# element-wise power on Array
print(a**3)
# matrix multiplication m*m*m 
print(m**3) 

[[ 1  8]
 [27 64]]
[[ 37  54]
 [ 81 118]]


In [38]:
# transpose of the matrix 
print(m.T) 
# conjugate transpose (differs from .T for complex matrices) 
print(m.H) 
# inverse matrix 
print(m.I) 

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
