In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 0])
zero_atAll = np.all((arr == 0))
cnt_zero = np.count_nonzero(arr)
if zero_atAll:
    print('Array contains only 0')
else:
    print('Array has non-zero items too')
    print("Number of non-zeroes items in array : ", cnt_zero)


Array has non-zero items too
Number of non-zeroes items in array :  6


In [12]:
import numpy as np 
arr = np.array([70 , 80 , 90, 80 ,90 ])
print("mean of arr : ", np.mean(arr))
print("median of arr : ", np.median(arr))

mean of arr :  82.0
median of arr :  80.0


In [3]:
import numpy as np
def age(lis,today):
    for i in lis:
        y=np.datetime64(i)-np.datetime64(today)
        z=y.astype(int)/366
        if round(z)==18:
            print('First')
        elif round(z)==19:
            print('Second')
        elif round(z)==20:
            print('Third')
        else:
            print('Fourth')

In [7]:
age(['2001-12-21','2002-08-12'],'2021-05-07')

Fourth
Fourth


In [3]:
import numpy as np
arr2D = np.array([[11, 12, 13, 22], [21, 7, 23, 14], [31, 10, 33, 7]])
print('2D Numpy Array')
print(arr2D)
sortedArr = arr2D[arr2D[:,0].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

2D Numpy Array
[[11 12 13 22]
 [21  7 23 14]
 [31 10 33  7]]
Sorted 2D Numpy Array
[[11 12 13 22]
 [21  7 23 14]
 [31 10 33  7]]
